# Generated by Django 6.0.4 on 2026-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_train',
            name='seats',
            field=models.IntegerField(default=100),
        ),
    ]
